os: linux
dist: bionic
language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

install:
  - npm ci
  - npm i eslint-plugin-import@^2.22.1

stages:
  - name: lintjs
  - name: tests

before_script:
  - http-server -s & # start a Web server

jobs:
  include:
    - stage: lintjs
      name: "JS Code Style Check"
      script:
        - eslint core/*.js components/**/*.js apps/heatmap/*.js apps/labeling/*.js apps/loader/*.js apps/model/*.js apps/segment/*.js apps/model/**/*.js apps/segment/**/*.js apps/viewer/*.js --quiet --max-warnings=0
        - yamllint .travis.yml

    - stage: tests
      name: Unit Tests
      script:
        - mocha test --recursive --exit

